import React from "react";
import ReactDOM  from "react-dom";
import "jquery";
import "popper.js/dist/umd/popper";
import "bootstrap/dist/js/bootstrap";
import "bootstrap/dist/css/bootstrap.css";
import App from "./App";
import "./index.css";
import "font-awesome/css/font-awesome.css";
var element = <button class= "btn btn-danger">HelloWorld</button>;
var element2 = <div>this is tony doing its things</div>;
ReactDOM.render(<App/>, document.getElementById("root"));
